### ISSUE TITLE
chào bạn

### ISSUE THREAD

**Issue by xiketuan** [thanhhau097/ml_project_template#1]
Mình nhớ là bạn có link youtube hướng dẫn đúng ko bạn? có thể cho mình xin link, vì giờ tìm không thấy bài trên face.
Cảm ơn!

**Comment by thanhhau097** [comment]
chào bạn, video hướng dẫn thử nghiệm trên máy local mình để ở đây: https://www.youtube.com/watch?v=bvIth6EPL7U&t=
